### ISSUE TITLE
NET usage error spamming HA log

### ISSUE THREAD

**Issue by Morphy99** [Sanderhuisman/docker_monitor#1]
I'm getting this in the HA log constantly:
`[custom_components.docker_monitor] Cannot grab NET usage for container 08849f316920fc12362fbdbdgdashdgasjdggsd4f151eb778d6af05a1836b0495 ('networks')`

I don't have network monitoring enabled either:
    monitored_conditions:
      - container_memory_usage
      - container_memory_percentage_usage
      - container_cpu_percentage_usage

**Comment by Sanderhuisman** [comment]
The log you mention is logged under the `info` level. In production, you normally do not want to see this information such that you set the global log level to `warning` or `error`. But I will revise the logging  of the component

**Comment by Morphy99** [comment]
Yea I get that. It is like every 10 seconds though so it just makes it harder to go through the HA logs when debugging. Thanks for looking at it :)

**Comment by ualex73** [comment]
@Morphy99 I suspect your container is running in network mode "host". In such situation Docker doesn't give any network stats (I fixed that warning in my version, it auto-detects the network mode and decide on that to report or not).

**Comment by Sanderhuisman** [comment]
If you have a fix, just make a pull request and I will get it in;)

**Comment by ualex73** [comment]
https://github.com/Sanderhuisman/docker_monitor/pull/4

But it should be technically gone, with the new develop version ... don't include the network items ;-)

**Comment by Sanderhuisman** [comment]
Fixed in development branch
