### ISSUE TITLE
Feature: Number of active and total containers

### ISSUE THREAD

**Issue by ualex73** [Sanderhuisman/docker_monitor#10]
I will look into making this a pull request, but having a sensor for number of active/total containers would be handy. Then I can remove Glances ;)

**Comment by Sanderhuisman** [comment]
I'm halfway done with this one ;)

**Comment by ualex73** [comment]
Do you still want me to create a pull request for this one? ;-)

**Comment by Sanderhuisman** [comment]
You can, however I just finished implementing this one. Just create a pull request and I will merge our implementations.

Do you have discord? You can find me as sanderhuisman#7527

**Comment by ualex73** [comment]
Done:
https://github.com/Sanderhuisman/docker_monitor/pull/12

I normally don't use Discord much, but my account is uAlex73#4533

**Comment by Sanderhuisman** [comment]
The info you where looking for is also available in the docker info function. My implementation is available in pull request #13. This also shows the number of containers in each state
