### ISSUE TITLE
Wrong memory usage when container has huge memory changes

### ISSUE THREAD

**Issue by ualex73** [Sanderhuisman/docker_monitor#18]
I am comparing/checking the memory usage shown in docker_monitor and via 'docker stats' and i have a few containers using a lot of memory and also 1 with a memory leak (camera bug in HA).

I added some logging around the memory reporting in the docker_monitor, i am checking the 'docker stats' output and using 'top'. The 'docker stats' and 'top' are the same, but the memory reported by 'docker_monitor' is slowing staying behind on the 'old' value.

```
$ docker stats --no-stream hass-test unifi
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
ea7aaf2c7e24        hass-test           19.34%              229MiB / 31.28GiB     0.71%               124MB / 6.6MB       41kB / 144MB        86
c2551e57f13c        unifi               0.91%               795.4MiB / 31.28GiB   2.48%               32.4MB / 4.15MB     17.6MB / 357MB      106
```
The output of docker_monitor logging at the same time:
```
$ grep Raw home-assistant.log| grep hass-test | tail -1; grep Raw home-assistant.log| grep unifi | tail -1
[custom_components.docker_monitor.helpers] hass-test - Raw Mem: 150.23  = 150.23 - 0.0
[custom_components.docker_monitor.helpers] unifi - Raw Mem: 803.06  = 932.07 - 129.01
```

You can notice 'hass-test' reports 150MB (wrong) vs 229MB (correct), it has a memory leak, so it goes up quickly. The 'unifi' reports 803MB (wrong) vs 795MB (correct), just a few MB off ... But still wrong.

Changing the stats call from streaming to none-streaming like:
```python
... = self._client.containers.get(name).stats(stream=False, decode=False)
```
Solves the problem, only then every stats call take roughly 2 seconds (not instant as it is now).

Maybe the streaming expect us to pick up the information every second/time, and not every 10 seconds? Possible the old data is supplied (10, 20, 30, 40, 50, 60, 70 seconds old?)?

The stream call itself is a blocking call, which makes it unhandy with a single thread. There is an asyncio version of a docker api: https://github.com/aio-libs/aiodocker

**Comment by Martinvdm** [comment]
Got sort of same issues with cpu values, some containers have more then 100% cpu for some while as docker stats giving e.g. 26% at the moment

**Comment by ualex73** [comment]
Switched over to my own component ;-) So this one can be closed.
