### ISSUE TITLE
Invalid configuration for HA 0.105.2

### ISSUE THREAD

**Issue by obelix05** [Sanderhuisman/docker_monitor#27]
Hello,
currently I'm unable to use docker monitor in my HA setup. If I run the "Check Config" script it returns:

```
Configuration invalid
Invalid config for [docker_monitor]: [containers] is an invalid option for [docker_monitor]. Check: docker_monitor->docker_monitor->containers. (See /config/configuration.yaml, line 306).
```
My configuration looks like this:
```
[306] docker_monitor:
[307]   containers:
[308]     - home-assistant
[309]     - nginx
[310]     - zigbee2mqtt
[311]   monitored_conditions:
[312]     - utilization_version
[313]     - container_status
[314]     - container_image
[315]     - container_memory_usage
[316]     - container_memory_percentage_usage
[317]     - container_cpu_percentage_usage
```
I installed docker monitor 0.1.2 using HACS 0.21.1

Can someone help me out?

**Comment by GuyKh** [comment]
I think you better point out what is it on  line #306.
But as a principle -- see the principle example from here: https://github.com/Sanderhuisman/docker_monitor/blob/develop/README.md
I think it's updated there

**Comment by obelix05** [comment]
I updated my report on the top and add line numbers to my config.
I had referred to the instructions here on master branch: https://github.com/Sanderhuisman/docker_monitor/blob/master/README.md
because it's also linked in the HACS overview. But thanks for the hint!
Can you please update the readme on master also?

**Comment by GuyKh** [comment]
The thing is that version 0.12 is later than the code in master and includes the new format.
I agree that the master should be aligned with the latest package (0.12) - @Sanderhuisman

**Comment by Sanderhuisman** [comment]
I agree as well
