### ISSUE TITLE
Container Network Total Up/Down Unavailable

### ISSUE THREAD

**Issue by squirtbrnr** [Sanderhuisman/docker_monitor#32]
Maybe this was discussed somewhere and I missed it, but I noticed any container I have with the option `--net=host` fails to gather network stats.  Containers that use the docker network and port forward work just fine.  Is there a work around to get network total stats for containers using the host interface/network?

**Comment by ualex73** [comment]
No, there is no network information available if "--net=host" is used. So that can not be fixed/improved.
